# CDAE
sweep_count: 100
method:     grid # grid, random, bayes
name:       cdae_grid_sweep
metric: 
  goal:     minimize # minimize, maximize
  name:     valid_loss # valid_MAP@K
parameters:
  # batch_size: ##########[COMMON]###############
  #   values: [16, 32, 64]
  # lr:
  #   values: [1e-1, 1e-3, 1e-4, 1e-5]
  # optimizer:
  #   values: [adam, adamw]
  # weight_decay:
  #   values: [1e-1, 1e-3, 1e-5]
  neg_times: ###########[MODEL]###############
    values: [1, 5, 10]
  hidden_size:
    values: [32, 64, 128, 256, 512, 1024]
  corruption_level:
    values: [.1, .3, .4, .5, .6, .9]
  hidden_activation:
    values: [sigmoid, identity]
