# CDAE
sweep_count: 100
method:     grid # grid, random, bayes
name:       mf_grid_sweep
metric: 
  goal:     minimize
  name:     valid_loss
parameters:
  # batch_size: ##########[COMMON]###############
  #   values: [16, 32, 64]
  # lr:
  #   values: [1e-1, 1e-3, 1e-4, 1e-5]
  optimizer:
    values: [adam, adamw]
  # weight_decay:
  #   values: [1e-1, 1e-3, 1e-5]
  embed_size: ###########[MODEL]###############
    values: [32, 64, 128, 256, 512, 1024]
