# run config
seed:       42 
shuffle:    True
model_dir:  outputs/models
submit_dir: outputs/submissions
data_dir:   data/
log_dir:    logs/

# mlflow config
exp:        True # True/ False
project:    YelpRecommendation
notes:      "..."

# train config
device:     cpu # cpu
epochs:     10
batch_size: 32
lr:         0.001
optimizer:  adamw
loss:       bce 
patience:   5
top_n:      10

# model config
model_name: CDAE
hidden_size:    64
corruption_level: 0.6
hidden_activation:  sigmoid
output_activation:  sigmoid
